Code/rails/blog/config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :article
  resources :authors

end

Code/rails/blog/app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :author
	validates :headline, presence: true
	validates :content, presence: true
	validates :author_id, presence: true
	validates :photo_url, presence: true
	validates :author, length: {
		maximum: 25,
		too_long: 'way too long of a name'
	}
	validate_length_of :author, minimum: 2
end

Code/rails/blog/app/models/author.rb
class Author < ActiveRecord::Base
end

Code/rails/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all()
	end

	def show
		@article = Article.find(params[:id])
	end
end

Code/rails/blog/app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<h1> <%=link_to article.headline, article_path(article.id) %> </h1>
	<h3>by: <%=article.author.name %> </h3>
	<%= image_tag article.photo_url, width: 200 %>
	<p> <%= article.content %> </p>
	<br>
<% end %>

<%= link_to "Add Article", new_article_path %>

Code/rails/blog/app/views/articles/show.html.erb
<h1> <%= @article.headline %> </h1>
<h3>by: <%=@article.author.name %> </h3>
<%= image_tag @article.photo_url, width: 200 %>
<p> <%= @article.content %> </p>

<%= link_to 'edit', edit_article_path %>
<%= link_to 'back', articles_path %>

Code/rails/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>