Code/rails/library/config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books
  resources :authors

end

Code/rails/library/app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books
end

Code/rails/library/app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :author
	validates :title, presence: true
	validates :author_id, presence: true
	validates :status, presence: true
	validates :title, length: {
		maximum: 20,
		too_long: "Too long"
	}
	validates_length_of :title, minimum: 3
end

Code/rails/library/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	def show
		@author = Author.find(params[:id])
	end

end

Code/rails/library/app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		@books = Book.all()
	end

	def show
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.status
			@book.update(status: false)
		else
			@book.update(status: true)
		end
		redirect_to @book
	end	

	def book_params
		params.require(:book).permit(:status)
	end

end

Code/rails/library/app/views/authors/show.html.erb
<h1> <%= @author.name %> </h1>

<h3>List of Books by this author: </h3>

<ul>
	<% @author.books.each do |book| %>
	<li><%= link_to book.title, book_path(book)%></li>
	<% end %>
</ul>

Code/rails/library/app/views/books/index.html.erb
<h1> Welcom to the libary </h1>

<h3> List of Books </h3>
<ul>
<% @books.each do |book| %>
	<li><%=link_to book.title, book_path(book)%></li>
<% end %>
</ul>

Code/rails/library/app/views/books/show.html.erb
<h1><%= @book.title %></h1>
 <br>
<p> by <%= link_to @book.author.name, author_path(@book.author) %> </p>
<br>


<% if @book.status %>
<p> Status: In</p>
<%= form_for @book, url:{action: 'update'} do |f| %>
<%= f.submit 'Check out book' %>
<% end %>
<% else %>
<p> Status: Out</p>
<%= form_for @book, url:{action: 'update'} do |f| %>
<%= f.submit 'Return Book' %>
<% end %>
<% end %>

<br>	
<%= link_to 'Return to Main Menu', books_path %> 

Code/rails/library/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>